---
    - name: Install MySQL
      action: yum name={{ item }}
      with_items:
        - MySQL-python
        - mysql
        - mysql-server

    - name: copy my.cnf file 
      template: src=my.cnf.j2 dest=/etc/my.cnf

    - name: Start the MySQL service
      action: service name=mysqld state=started
